name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:

  # =========================
  # CI STAGE
  # =========================
  ci:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # 4. Run ML model
      - name: Run ML model
        run: |
          python model.py


      # 5. Run tests
      - name: Run tests
        run: |
          pytest


  # =========================
  # CD STAGE
  # =========================
  cd:

    # CD runs only when CI passes
    needs: ci

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4


      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5


      # Upload website
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .


      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
